services:
  db:
    image: postgres:14.1-alpine
    container_name: mineral_db
    env_file:
      - ./.env
    restart: always
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mineral
  app:
    build: ./
    ports: 
      - "3000:3000"
    container_name: mineral_app
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - mineral
  
networks:
  mineral:
    driver: bridge

volumes:
  pgdata: {}
    
