version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    container_name: mineral_db
    env_file:
      - ./.env
    restart: always
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - mineral
  app:
    build: ./
    ports: 
      - "3000:3000"
    container_name: mineral_app
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
    volumes:
      - ./:/app
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - mineral
  
networks:
  mineral: {}

volumes:
  pgdata: {}
    
