import type { Metadata } from "next";
import './admin.css'

// fonts

import { Roboto, Geist } from "next/font/google";

// 

import { Container } from "react-bootstrap";
import 'bootstrap/dist/css/bootstrap.min.css';

// fonts

const roboto = Roboto({
  subsets: ["latin"],
})

// 


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

      <Container className="h-100">
      {children}
      </Container>

  );
}
